version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DATABASE: "curation_api"
      POSTGRES_USER: "anoushkkharangate"
    
    ports:
      - 5432:5432