version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    environment:
      - DB_HOST=db
      - DB_NAME=curation_api
      - DB_USER=anoushkkharangate
      - DB_PASS=1234
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=curation_api
      - POSTGRES_USER=anoushkkharangate
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"